export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";

export const AUTH = "AUTH";
export const GET_DC_ID = "GET_DC_ID";
export const LOGOUT = "LOGOUT";
export const LIST_API = "LIST_API";
export const FETCH_DC_DETAILS = "FETCH_DC_DETAILS";
export const ADD_NEW = "ADD_NEW";
export const UPDATE = "UPDATE";
export const DELETE = "DELETE";
export const GET_INVOICE = "GET_INVOICE";
export const FETCH_INVOICE_BY_ID = "FETCH_INVOICE_BY_ID";
export const GET_ITEMS = "GET_ITEMS";
export const GET_USER_LIST = "GET_USER_LIST";
export const CUSTOM_LINE_ITEM = "CUSTOM_LINE_ITEM";
export const GET_VENDOR_LIST = "GET_VENDOR_LIST";

export const REFRESHTOKEN = "REFRESHTOKEN";
export const CHANGE_REQUEST = "CHANGE_REQUEST";

export const CREATE_USER = "CREATE_USER";

export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const SHOW_NOTIFICATION_BADGE = "SHOW_NOTIFICATION_BADGE";

export const FETCH_TRANSACTION_DETAILS = "FETCH_TRANSACTION_DETAILS";

export const VENDOR_DUE_REPORT = "VENDOR_DUE_REPORT";
export const DC_ID_REPORT = "DC_ID_REPORT";

export const WITHDRAW_AMOUT = "WITHDRAW_AMOUT";
export const GET_WITHDRAWS = "GET_WITHDRAWS";
export const UPDATE_WITHDRAW = "UPDATE_WITHDRAW";

export const VENDOR_CREATED = "VENDOR_CREATED";
export const SET_VENDOR_USER = "SET_VENDOR_USER";
export const ALL_VENDORS = "ALL_VENDORS";
export const START_WITHDRAW_UPDATE_LOADING = "START_WITHDRAW_UPDATE_LOADING";
export const END_WITHDRAW_UPDATE_LOADING = "END_WITHDRAW_UPDATE_LOADING";
